app:
  seed: false
---
spring:
  application:
    name: home-services-demo
  profiles:
    default: dev
server:
  port: ${PORT:8081}

---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/homesvc}
app:
  seed: true
---
spring:
  config:
    activate:
      on-profile: render
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
app:
  seed: false