name: Image

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'

jobs:
  publish-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # allow pushing to GHCR
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Maven path (auto-skip if no pom.xml)
      - name: Build & push (Maven + Jib)
        if: hashFiles('**/pom.xml') != ''
        run: >
          mvn -B -DskipTests
          -Djib.to.image=ghcr.io/${{ github.repository }}:${{ github.sha }}
          -Djib.to.tags=latest
          -Djib.to.auth.username=${{ github.actor }}
          -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }}
          jib:build

      # Gradle path (auto-skip if no build.gradle)
      - name: Build & push (Gradle + Jib)
        if: hashFiles('**/build.gradle*') != ''
        run: >
          ./gradlew -x test jib
          -Djib.to.image=ghcr.io/${{ github.repository }}:${{ github.sha }}
          -Djib.to.tags=latest
          -Djib.to.auth.username=${{ github.actor }}
          -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }}
